### ISSUE TITLE
Deploy v7.0.1 to docker hub

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia_http#97]

**Comment by ghallak** [comment]
@davidyuk There was a bug preventing the deployment of the new release to docker hub.

The bug was fixed here https://github.com/aeternity/aesophia_http/commit/0676e57b1e72088a2a8df02ebb53289837d3d399.

And you can find the new docker image here [docker pull aeternity/aesophia_http:v7.0.1](https://hub.docker.com/layers/aesophia_http/aeternity/aesophia_http/v7.0.1/images/sha256-6fe70c52e50ddcc4c0f3a6254ea28ec82bb32543dbca18ad987d84fac887a4d6?context=explore).
